# Module

ifdef USE_CMSIS
	CMSIS_TARGET  = cmsis
	$(CMSIS_TARGET)_CFLAGS  = $(CFLAGS)
	$(CMSIS_TARGET)_CFLAGS += -DARM_MATH_CM4 -D__FPU_PRESENT
	$(CMSIS_TARGET)_SRCS    = \
		$(BASEDIR)/../CubeMX/Drivers/CMSIS/DSP_Lib/Source/CommonTables/arm_common_tables.c \
		$(BASEDIR)/../CubeMX/Drivers/CMSIS/DSP_Lib/Source/FastMathFunctions/arm_sin_f32.c
	$(CMSIS_TARGET)_INCS    = \
		-I$(BASEDIR)/../CubeMX/Drivers/CMSIS/Device/ST/STM32F4xx/Include \
		-I$(BASEDIR)/../CubeMX/Drivers/CMSIS/Include
	THIRD_PARTIES += $(CMSIS_TARGET)
endif

ifdef USE_CUBEMX
	CUBEMX_TARGET  = cubemx
	$(CUBEMX_TARGET)_CFLAGS  = $(CFLAGS)
	$(CUBEMX_TARGET)_CFLAGS += -DUSE_HAL_DRIVER -DSTM32F469xx
	$(CUBEMX_TARGET)_SRCS    = \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c \
		$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
		$(BASEDIR)/../CubeMX/Src/stm32f4xx_hal_msp.c \
		$(BASEDIR)/../CubeMX/Src/system_stm32f4xx.c \
		$(BASEDIR)/../CubeMX/Src/main.c
	$(CUBEMX_TARGET)_INCS = \
		-I$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Inc \
		-I$(BASEDIR)/../CubeMX/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
		-I$(BASEDIR)/../CubeMX/Drivers/CMSIS/Device/ST/STM32F4xx/Include \
		-I$(BASEDIR)/../CubeMX/Drivers/CMSIS/Include \
		-I$(BASEDIR)/../CubeMX/Inc
	THIRD_PARTIES += $(CUBEMX_TARGET)
endif

ifdef USE_EMWIN
	EMWIN_TARGET = emwin
	$(EMWIN_TARGET)_CFLAGS  = $(CFLAGS)
	$(EMWIN_TARGET)_CFLAGS += #-DOS_SUPPORT
	$(EMWIN_TARGET)_SRCS    = \
		$(BASEDIR)/../emWin/Config/GUIConf.c \
		$(BASEDIR)/../emWin/Config/LCDConf.c \
		$(BASEDIR)/../emWin/OS/GUI_X.c
	$(EMWIN_TARGET)_INCS = \
		-I$(BASEDIR)/../emWin/inc \
		-I$(BASEDIR)/../emWin/Config
	LIBS += $(BASEDIR)/../emWin/Lib/STemWin532_CM4_GCC.a
	THIRD_PARTIES += $(EMWIN_TARGET)
endif

ifdef USE_UGFX
	GFXLIB = $(BASEDIR)/../ugfx
	export GFXLIB
	include $(GFXLIB)/boards/base/Olimex-STM32-LCD/board.mk
	include $(GFXLIB)/gfx.mk

	INC += $(foreach d, $(GFXINC), -I$d)
	SRCS +=$(GFXSRC)
endif
